version: "0.0.1.{build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat build

branches:
  only:
    - master
    - dev

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true

artifacts:
  - path: build\libs
    name: "originiumcraft-$(APPVEYOR_BUILD_VERSION)"